#!/bin/bash

file=$(jq -r ".file" data/oderint.json)
event=$(jq -r ".event" data/oderint.json)
script=$(jq -r ".script" data/oderint.json)

dir=$(dirname $file)
tempFile="temp.out"

fileName=${file##*/}
fileExt=${file##*.}
