#!/bin/bash

source data/config.sh

checkFileExt() {
    case $fileExt in
        c | cpp | js)
            clang-format -i -style=Google $path
            ;;
        py)
            black -q $path
            ;;
        *)
            if [[ -x $path ]]; then
                shfmt -w -sr -ci -i=4 $path
            else
                echo "$fileExt extension not defined"
                exit 1
            fi
            ;;
    esac
}

if [[ -d $path ]]; then
    prettier -w --loglevel error $path
else
    checkFileExt
fi
