#!/bin/bash

source data/config

case $fileExt in
    c)
        if gcc $file -o $tempFile; then
        	./$tempFile
        	rm $tempFile
        fi
        ;;
    cpp)
        if g++ $file -o $tempFile; then
        	./$tempFile
        	rm $tempFile
        fi
        ;;
    py)
        python $file
        ;;
    js)
        node $file
        ;;
    *)
        echo "$fileExt extension not defined"
        exit 1
        ;;
esac
