#!/bin/bash

case expression in  
    c)
        if gcc $file -o $tempFile; then
        	./$tempFile
        	rm $tempFile
        fi
        ;;
    cpp)
        if g++ $file -o $tempFile; then
        	./$tempFile
        	rm $tempFile
        fi
        ;;
    py)
        python $file
        ;;
    pattern-n)
        statements  
        ;;  
    *)  
        statements  
        ;;  
esac
