#!/bin/bash

source data/config.sh

checkFileExt() {
    case $fileExt in
        c)
            if gcc $path -o $tempFile; then
                ./$tempFile
                rm $tempFile
            fi
            ;;
        cpp)
            if g++ $path -o $tempFile; then
                ./$tempFile
                rm $tempFile
            fi
            ;;
        go)
            go run $path
            ;;
        js)
            node $path
            ;;
        py)
            python $path
            ;;
        sh)
            /bin/bash $path
            ;;
        *)
            if [[ -x $path ]]; then
                cd $(dirname $path)
                $path
            else
                echo "$fileExt extension not defined"
                exit 1
            fi
            ;;
    esac
}

if [[ -d $path ]]; then
    if ! lsof -i:$port &> /dev/null; then
        live-server --quiet --port=$port $path
    fi
else
    checkFileExt
fi
